// <auto-generated />
using System;
using Hospital.Dados.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital.Dados.Migrations
{
    [DbContext(typeof(HospitalContext))]
    [Migration("20230922204513_AdicionaColunaAcompanhanteEmPaciente")]
    partial class AdicionaColunaAcompanhanteEmPaciente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Hospital.Dominio.Entidades.Consulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Data");

                    b.Property<int>("MedicoId")
                        .HasColumnType("int")
                        .HasColumnName("MedicoId");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int")
                        .HasColumnName("PacienteId");

                    b.HasKey("Id");

                    b.ToTable("Consultas", (string)null);
                });

            modelBuilder.Entity("Hospital.Dominio.Entidades.Medico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<int>("Especialidade")
                        .HasColumnType("int")
                        .HasColumnName("Especialidade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("Medicos", (string)null);
                });

            modelBuilder.Entity("Hospital.Dominio.Entidades.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Acompanhante")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .HasColumnName("Acompanhante");

                    b.Property<int>("Idade")
                        .HasColumnType("int")
                        .HasColumnName("Idade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("Pacientes", (string)null);
                });

            modelBuilder.Entity("Hospital.Dominio.Entidades.Prescricao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<int>("ConsultaId")
                        .HasColumnType("int")
                        .HasColumnName("ConsultaId");

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Diagnostico");

                    b.Property<int>("TratamentoId")
                        .HasColumnType("int")
                        .HasColumnName("TratamentoId");

                    b.HasKey("Id");

                    b.ToTable("Prescricoes", (string)null);
                });

            modelBuilder.Entity("Hospital.Dominio.Entidades.Tratamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("ModoDeUso")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ModoDeUso");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Nome");

                    b.Property<int>("Periodo")
                        .HasColumnType("int")
                        .HasColumnName("Periodo");

                    b.HasKey("Id");

                    b.ToTable("Tratamentos", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
